### ISSUE TITLE
Sending callback notifications to a service outside the NEF emulator

### ISSUE THREAD

**Issue by dcamps** [medianetlab/NEF_emulator#80]
Hi,

I am wondering if there is any way we can get notification callbacks out of the NEF emulator into another service that we have in localhost. 

For example: I have a service outside the NEF emulator listening to http://localhost:80/api/v1/utils/monitoring/callback. However, I see that the notifications are only handled inside the NEF emulator, i.e. they are displayed in the dashboard, but never reach the external service. 

If it is not currently possible to instruct NEF emulator to issue the callback to an external service, could you kindly indicate how such functionality could be added?

BR

Daniel

**Comment by JFrgs** [comment]
Hello Daniel, 

You can receive notification callbacks from the NEF emulator to another service, whether it is hosted on localhost or a remote machine. To achieve this, you need to specify the appropriate URL of your service's server in the notification destination attribute of the POST request when creating a subscription. This will ensure that the notifications are sent to the desired location.

### Example: 

Below is an example illustrating how your external service can submit a subscription to retrieve location updates (callback notifications) for a UE with the external ID "[10003@domain.com](10003@domain.com)" during a handover to another cell
```
{
  "externalId": "10003@domain.com",
  "notificationDestination": "http://localhost:8090/myservice/monitoring_callback",
  "monitoringType": "LOCATION_REPORTING",
  "maximumNumberOfReports": 1000,
  "monitorExpireTime": "2024-06-01T12:55:27.587Z"
}
```
The `notificationDestination` parameter should be set to the URL of your service's endpoint (your service should act as a server in this case) where the notifications will be delivered.

Hope this helps!

Dimitris

**Comment by dcamps** [comment]
Thanks @tgogos , @JFrgs ,

I just changed localhost by a valid IP address and started receiving the notifications in my service.

BR

Daniel
